# Generated by Django 4.2.1 on 2023-05-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambioestado',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='estado',
            name='cambioEstado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='encuestas.cambioestado'),
        ),
    ]
