# Generated by Django 4.2.1 on 2023-05-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_cambioestado_estado_id_estado_cambioestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='cambioEstado',
        ),
    ]
