# Generated by Django 4.2.1 on 2023-05-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_cambioestado_estado_alter_estado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestadecliente',
            name='llamada',
        ),
        migrations.AlterField(
            model_name='llamada',
            name='respuestasDeEncuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='llamada', to='encuestas.respuestadecliente'),
        ),
        migrations.AlterField(
            model_name='respuestadecliente',
            name='respuestasDeEncuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='respuestaDeCliente', to='encuestas.respuestaposible'),
        ),
    ]
