# Generated by Django 4.2.1 on 2023-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_remove_respuestadecliente_llamada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamada',
            name='respuestasDeEncuesta',
        ),
        migrations.AddField(
            model_name='llamada',
            name='respuestasDeEncuesta',
            field=models.ManyToManyField(default=None, related_name='llamada', to='encuestas.respuestadecliente'),
        ),
    ]
