# Generated by Django 4.2.1 on 2023-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_remove_llamada_respuestasdeencuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
